name: Update coaching feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # hourly

permissions:
  contents: write   # allow pushing the generated JSON

concurrency:
  group: coaching-feed
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - run: npm ci || npm i

      # Run the scraper; don't fail the job if it errors
      - name: Run scraper
        run: node scripts/coach-scraper.mjs
        continue-on-error: true

      # Always try to commit whatever JSON exists
      - name: Commit & push if changed
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/coaching.json
          git commit -m "chore: update coaching feed [skip ci]" || echo "No changes."
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }} || echo "Nothing to push"

      # Save the produced JSON as an artifact for easy inspection
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coaching-json
          path: docs/data/coaching.json
