name: Update coaching feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - ".github/workflows/scrape.yml"

concurrency:
  group: coaching-feed
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci || npm i
      - run: npm run scrape

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/coaching.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: update coaching feed [skip ci]"
            git push
          fi
